.gitlab-ci.yml
=> Use docker base images

micro_ros_setup/config/client_uros_packages.repos, micro_ros_setup/scripts/create_client_ws.sh
Provide same command line as the agent scripts.
=> Allow client ws creation for demos

micro_ros_setup/config/client_uros_packages.repos, micro_ros_setup/scripts/create_client_ws.sh
Reverts micro-ROS/micro-ros-build#22
=> Revert "Allow client ws creation for demos"

.gitlab-ci.yml, micro_ros_setup/CMakeLists.txt, micro_ros_setup/config/client-host-colcon.meta, micro_ros_setup/config/client_host_packages.repos, micro_ros_setup/config/client_uros_packages.repos, micro_ros_setup/docker/Dockerfile.host_client, micro_ros_setup/scripts/create_agent_ws.sh, micro_ros_setup/scripts/create_client_ws.sh, micro_ros_setup/scripts/create_host_client_ws.sh
Added scripts to create a client WS in the host machine.
Added micro-ROS-demos repository.
Also unified create_client_ws.sh script with the rest of the create_* scripts.
=> Added scripts to create local client ws

micro_ros_setup/scripts/build_firmware.sh
This will add the fast-build changes to the dashing branch.
=> Add fast-build to dashing

micro_ros_setup/README.md
This PR updated the readme with some command fixes and ROS 2 Distros selection
=> Updated Readme

micro_ros_setup/README.md, micro_ros_setup/config/agent-colcon.meta, micro_ros_setup/config/agent_uros_packages.repos, micro_ros_setup/config/freertos/crazyflie21/client_uros_packages.repos, micro_ros_setup/config/host/generic/client-host-colcon.meta, micro_ros_setup/config/host/generic/client_host_packages.repos, micro_ros_setup/config/nuttx/generic/client_uros_packages.repos
This pull request updates the *.repos to Dashing.
=> Update repos to Dashing

micro_ros_setup/README.md, micro_ros_setup/config/agent-colcon.meta, micro_ros_setup/config/agent_uros_packages.repos, micro_ros_setup/config/freertos/crazyflie21/client_uros_packages.repos, micro_ros_setup/config/host/generic/client-host-colcon.meta, micro_ros_setup/config/host/generic/client_host_packages.repos, micro_ros_setup/config/nuttx/generic/client_uros_packages.repos
Once merged we can delete the branch `feature/avoid_filesystem_and_allocation` from https://github.com/micro-ROS/rcutils
=> Update merged branch.

micro_ros_setup/config/agent_uros_packages.repos, micro_ros_setup/config/freertos/crazyflie21/client_uros_packages.repos, micro_ros_setup/config/host/generic/client_host_packages.repos, micro_ros_setup/config/nuttx/generic/client_uros_packages.repos
This pull request updates Micro-XRCE-DDS' versions in .repos.
=> Micro-XRCE-DDS versions

micro_ros_setup/config/agent_uros_packages.repos, micro_ros_setup/config/freertos/crazyflie21/client-colcon.meta, micro_ros_setup/config/freertos/crazyflie21/client_uros_packages.repos, micro_ros_setup/config/host/generic/client-host-colcon.meta, micro_ros_setup/config/host/generic/client_host_packages.repos, micro_ros_setup/config/nuttx/generic/client-colcon.meta, micro_ros_setup/config/nuttx/generic/client_uros_packages.repos
This pull request fixes Micro-CDR installation.
=> Fix Micro-CDR installation

.github/workflows/ci.yml
Create a GitHub hosted CI system.
Currently doing tests on https://github.com/BorjaOuterelo/micro-ros-build/pull/2. Once that pull request passes CI OK I will merge this one.
=> WIP: Add GitHub actions.

micro_ros_setup/config/client_ros2_packages.txt
This pull request fixes the issue #61.
=> Fix typesupport generation

micro_ros_setup/config/freertos/crazyflie21/client-colcon.meta, micro_ros_setup/config/host/generic/client-host-colcon.meta, micro_ros_setup/config/nuttx/generic/client-colcon.meta
This pull request removes common package configuration that was move to colcon.pkgs.
=> Simplify metas

micro_ros_setup/config/client_ros2_packages.txt, micro_ros_setup/config/host/generic/build.sh, micro_ros_setup/config/host/generic/client-host-colcon.meta
This pull request fixes issue #57.
=> Fix -fPIC error and metas configuration

micro_ros_setup/scripts/yaml_filter.py
This pull request fixes issue #64.
=> Fix yaml_filter.py tool

micro_ros_setup/config/host/generic/client-host-colcon.meta
This pull request changes the host configuration in order to build micro-ROS libraries as shared libs and increases the number of client/server for parameters applications.
=> Host client configuration

micro_ros_setup/config/freertos/crazyflie21/client-colcon.meta, micro_ros_setup/config/freertos/crazyflie21/configure.sh, micro_ros_setup/config/freertos/olimex-stm32-e407/client-colcon.meta, micro_ros_setup/config/freertos/olimex-stm32-e407/configure.sh, micro_ros_setup/config/zephyr/generic/configure.sh
Adds a new Micro XRCE-DDS external transport policy. Make sure that it is merged with:
=> New external transport approach

.github/workflows/ci.yml, micro_ros_setup/config/freertos/crazyflie21/create.sh, micro_ros_setup/config/freertos/olimex-stm32-e407/create.sh, micro_ros_setup/config/zephyr/generic/client-colcon.meta
Adaptation of CI to new micro-ROS generic build system, using github actions.
=> #7810 CI for generic build system.

.github/workflows/ci.yml, micro_ros_setup/config/freertos/crazyflie21/package.xml, micro_ros_setup/config/nuttx/generic/package.xml
same as https://github.com/micro-ROS/micro-ros-build/pull/82 but testing the new CI
=> Added ed dependency to rosdep v2

micro_ros_setup/config/freertos/crazyflie21/client_uros_packages.repos, micro_ros_setup/config/freertos/olimex-stm32-e407/client_uros_packages.repos, micro_ros_setup/config/zephyr/generic/client_uros_packages.repos
Set RMW branch to dashing in all .repos
=> Updating rmw branch to dashing

micro_ros_setup/README.md
This PR fixes some misspelling and adds a configuration table in the setup readme.
=> Fix README

.github/workflows/ci.yml, micro_ros_setup/README.md, micro_ros_setup/config/zephyr/generic/build.sh, micro_ros_setup/config/zephyr/generic/configure.sh, micro_ros_setup/config/zephyr/generic/create.sh, micro_ros_setup/config/zephyr/generic/flash.sh, micro_ros_setup/config/zephyr/generic/package.xml
=> Added Zephyr simulator

micro_ros_setup/config/zephyr/generic/flash.sh
=> Fix Zephyr host flash script

micro_ros_setup/config/zephyr/generic/create.sh
This PR updates zephyr branch with ToF sensor driver
=> Update Zephyr temporal branch

micro_ros_setup/scripts/create_agent_ws.sh
This PR fix agent installation when not installed isolated
=> Fix Agent installation when uros host

.github/workflows/ci.yml, micro_ros_setup/config/nuttx/generic/uros_packages.repos
=> NuttX CI fix

micro_ros_setup/config/freertos/crazyflie21/flash.sh
This PR fixes the Crazyflie flash script
=> Fix Crazyflie flash

micro_ros_setup/config/freertos/crazyflie21/board.repos, micro_ros_setup/config/freertos/crazyflie21/build.sh, micro_ros_setup/config/freertos/crazyflie21/client-colcon.meta
This PR updates CF firm to a newer commit and fix a fast build issue
Related to, check before merge:
=> Update CF firm commit and fix fast build

micro_ros_setup/config/zephyr/generic/build.sh, micro_ros_setup/config/zephyr/generic/configure.sh
This PR adds support for serial transport on zephyr and adds nucleo_f401re board
=> Zephyr serial transport and nucleo_f401re

micro_ros_setup/config/zephyr/generic/flash.sh, micro_ros_setup/config/zephyr/generic/supported_platforms
Failed to post-sign my original commits after I pushed them unsigned.
Commits are identical to #119 , but now there are no not-signed commits in it.
Sorry for the inconvenience.
Cheers
=> Add nucleo_f401re to flash script and supported_plattform for zephyr - RETRY

micro_ros_setup/config/zephyr/generic/configure.sh
This PR fixes UDP configuration in Zephyr
=> Fix zephyr udp

micro_ros_setup/config/freertos/crazyflie21/create.sh, micro_ros_setup/config/freertos/olimex-stm32-e407/create.sh, micro_ros_setup/config/nuttx/generic/create.sh, micro_ros_setup/config/zephyr/generic/create.sh, micro_ros_setup/scripts/create_firmware_ws.sh
This PR modifies some foxy repos
=> Foxy repos

micro_ros_setup/config/agent_uros_packages.repos
This PR updates the micro-ROS Agent for Foxy release
=> Updating branches

micro_ros_setup/config/freertos/crazyflie21/board.repos, micro_ros_setup/config/freertos/crazyflie21/client_uros_packages.repos, micro_ros_setup/config/freertos/crazyflie21/create.sh, micro_ros_setup/config/freertos/olimex-stm32-e407/board.repos, micro_ros_setup/config/freertos/olimex-stm32-e407/client-colcon.meta, micro_ros_setup/config/freertos/olimex-stm32-e407/client_uros_packages.repos, micro_ros_setup/config/freertos/olimex-stm32-e407/configure.sh, micro_ros_setup/config/freertos/olimex-stm32-e407/create.sh
This PR updates FreeRTOS build system to foxy
=> Updated freertos bs

micro_ros_setup/config/freertos/crazyflie21/build.sh, micro_ros_setup/config/freertos/olimex-stm32-e407/build.sh
This PR adds `-j$(nproc)` to the FreeRTOS builds
=> Increase build cores freertos

.github/workflows/ci.yml
This PR removes the workaround in Nuttx CI
=> Refactor Nuttx CI

.github/workflows/ci.yml, micro_ros_setup/config/freertos/nucleo_f446ze/board.repos, micro_ros_setup/config/freertos/nucleo_f446ze/client-colcon.meta, micro_ros_setup/config/freertos/nucleo_f446ze/client_uros_packages.repos, micro_ros_setup/config/freertos/nucleo_f446ze/configure.sh, micro_ros_setup/config/freertos/nucleo_f446ze/create.sh, micro_ros_setup/config/freertos/olimex-stm32-e407/build.sh
This PR updates the Nucleo F446ZE repos to foxy.
=> Update Nucleo F446ZE to Foxy

.github/workflows/ci.yml, micro_ros_setup/CMakeLists.txt, micro_ros_setup/scripts/build_agent.sh
=> Add specific script to build micro-ROS-Agent

config/freertos/crazyflie21/client_uros_packages.repos, config/freertos/esp32/client_uros_packages.repos, config/freertos/nucleo_f446ze/client_uros_packages.repos, config/freertos/olimex-stm32-e407/client_uros_packages.repos, config/nuttx/generic/client_uros_packages.repos, config/zephyr/generic/client_uros_packages.repos
This PR fixes the feature revert done here: https://gitlab.com/micro-ROS/ros_tracing/ros2_tracing/-/merge_requests/201
=> Fix rostracing branch

.github/CODEOWNERS, .github/workflows/ci.yml, README.md, config/freertos/list_apps.sh, config/freertos/nucleo_f746zg/board.repos, config/freertos/nucleo_f746zg/build.sh, config/freertos/nucleo_f746zg/client-colcon.meta, config/freertos/nucleo_f746zg/client_uros_packages.repos, config/freertos/nucleo_f746zg/configure.sh, config/freertos/nucleo_f746zg/create.sh, config/freertos/nucleo_f746zg/flash.sh, config/freertos/nucleo_f746zg/package.xml, config/zephyr/generic/build.sh, config/zephyr/generic/supported_platforms
Adding support for nucleo f746zg
=> Adding nucleo f746zg support to microros setup for FreeRTOS

scripts/create_firmware_ws.sh
Related to https://github.com/micro-ROS/micro_ros_setup/issues/204 and https://github.com/ament/ament_cmake/issues/285
=> Fix ament dependency

config/freertos/esp32/create.sh
No superuser permissions are guaranteed to perform these actions.
=> Apt packages shall not be installed by scripts

.github/CODEOWNERS, .github/workflows/ci.yml, README.md, config/freertos/nucleo_f446re/board.repos, config/freertos/nucleo_f446re/build.sh, config/freertos/nucleo_f446re/client-colcon.meta, config/freertos/nucleo_f446re/client_uros_packages.repos, config/freertos/nucleo_f446re/configure.sh, config/freertos/nucleo_f446re/create.sh, config/freertos/nucleo_f446re/flash.sh, config/freertos/nucleo_f446re/package.xml
* Based on already existing repository for nucleo F446ZE
=> Add support for nucleo F446RE

.github/workflows/ci.yml, .github/workflows/nightly.yml
This PR removes the nightly schedule for the CI and adds a new workflow for Nightly builds of foxy and rolling
=> Refactor nightly

README.md, config/freertos/esp32/configure.sh, config/freertos/nucleo_f446re/configure.sh, config/freertos/nucleo_f446ze/configure.sh, config/freertos/nucleo_f746zg/configure.sh, config/freertos/nucleo_f767zi/configure.sh, config/freertos/olimex-stm32-e407/configure.sh, config/zephyr/generic/configure.sh
=> Update configure step

config/host/generic/client-host-colcon.meta
Related: https://github.com/eProsima/Micro-XRCE-DDS-Client/pull/213
=> Fix RMW_UXRCE_STREAM_HISTORY host

config/freertos/nucleo_f746zg/flash.sh, config/freertos/nucleo_f767zi/flash.sh
Every script in this branch is kinda wrong, they are copypasta of olimex version.
=> fix f767zi flash script

config/host/generic/client-host-colcon.meta
* Add multithread configuration to host
* Auto stash before rebase of "origin/galactic"
* Update config/host/generic/client-host-colcon.meta
* Update config/host/generic/client-host-colcon.meta
=> Add multithread configuration to colcon.meta

config/nuttx/generic/flash.sh
Added the st-link-v2 support, checked ping-pong example tutorial and uploads fine.
=> Added support for st-link-V2

config/generate_lib/generic/build.sh
Related: https://github.com/micro-ROS/micro_ros_arduino/issues/391
=> Fix library generation error

config/agent_uros_packages.repos
Depends on https://github.com/micro-ROS/micro-ROS-Agent/pull/97
=> Simplify micro-ROS Agent build

config/freertos/crazyflie21/board.repos, config/freertos/crazyflie21/create.sh, config/freertos/crazyflie21/patchs/0001-Add-tx-queue-utilities.patch, config/freertos/crazyflie21/patchs/0001-Remove-assert.patch
Add functionality to crazyflie firmware using git patches:
- Get status of radio link tx queue
- Disable assert inside radio initialization
=> Update crazyflie firmware version

.github/workflows/ci.yml, .github/workflows/nightly.yml
=> Revert "Temporal fix for cmake update (#428)"

README.md
Repository pull should aim for ROS2 version branch
=> Fix branch version

config/client_uros_packages.repos, config/freertos/nucleo_f767zi/client-colcon.meta
fix version tag in client_uros_packages.repos
fix repeated flag in client-colcon.meta
=> [galactic-fix] fix typo in compiling description file.

.github/workflows/ci.yml, .github/workflows/nightly.yml
=> Fix CMake install in Jammy

.github/workflows/ci.yml, .github/workflows/nightly.yml
=> Remove Python 3.9

README.md
=> Fix readme rosdep

config/zephyr/generic/create.sh
Solves https://github.com/micro-ROS/micro_ros_setup/runs/6556381894?check_suite_focus=true
=> Fix pip uninstall error

.github/workflows/ci.yml, .github/workflows/nightly.yml, README.md, config/agent_uros_packages.repos, config/android/generic/client_uros_packages.repos, config/client_uros_packages.repos, config/freertos/crazyflie21/board.repos, config/freertos/esp32/board.repos, config/freertos/nucleo_f446re/board.repos, config/freertos/nucleo_f446ze/board.repos, config/freertos/nucleo_f746zg/board.repos, config/freertos/nucleo_f767zi/board.repos, config/freertos/olimex-stm32-e407/board.repos, config/host/generic/client_host_packages.repos, config/mbed/generic/board.repos, config/raspbian/generic/create.sh, config/renesas_ra/ra6m5/board.repos, config/zephyr/generic/board.repos, config/zephyr/generic/create.sh
Nightly test run: https://github.com/micro-ROS/micro_ros_setup/runs/6568548596
=> Humble release

config/host/generic/create.sh
=> Fix CI host

.github/workflows/nightly.yml
=> Fix Nightly CMake

config/raspbian/generic/configure.sh, scripts/create_ws.sh
=> Fix humble repos

config/android/generic/client_uros_packages.repos, config/client_ros2_packages.txt, config/client_uros_packages.repos, config/host/generic/client_host_packages.repos
Depends on:
https://github.com/micro-ROS/raspbian_apps/pull/19
MBed fix
=> Add rosidl_core
