- .gitlab-ci.yml
For branches, only run CI checks for the part that matches the branch name.
> Build agent and firmware separately

- micro_ros_setup/scripts/create_agent_ws.sh
As from today microxrcedds-agent could be resolved with rosdep:
https://discourse.ros.org/t/new-packages-for-ros-2-crystal-2019-09-19/10737
> Roll back the microxrcedds_agent workaround

- micro_ros_setup/config/nuttx/generic/client-colcon.meta
Solves issues building NuttX due to static memory usage too high with default configuration values.
> Add middleware configuration in colcon metas file.

- micro_ros_setup/config/freertos/crazyflie21/client_uros_packages.repos
- micro_ros_setup/config/freertos/olimex-stm32-e407/client_uros_packages.repos
- micro_ros_setup/config/nuttx/generic/client_uros_packages.repos
This pull request fixes issue #66.
The `ros2/rosidl_typesupport` upstream contains the fix in `uros/rosidl_typesupport`.
> Fix multiple typesupport error

- micro_ros_setup/config/agent_ros2_packages.txt
This pull request removes unnecesary packages for `micro-ROS-Agent`.
> Agent packages prune

- micro_ros_setup/README.md
This pull request fixes some misspellings in `micro_ros_setup` `README`.
Furthermore, it adds the `rosdep` instruction.
> Fix micro_ros_setup README

- .github/workflows/ci.yml
- micro_ros_setup/config/freertos/crazyflie21/client_uros_packages.repos
- micro_ros_setup/config/freertos/olimex-stm32-e407/client_uros_packages.repos
- micro_ros_setup/config/zephyr/generic/flash.sh
This PR refactors the flash script in order to use the Olimex ARM-USB-Tiny JTAG adapter
> Update zephyr Flash to Olimex support

- micro_ros_setup/config/host/generic/client-host-colcon.meta
- micro_ros_setup/config/zephyr/generic/create.sh
This PR manages the errors while upgrading CMake version in Zephyr and ask the user to install it manually in the case it can't install it
> Zephyr Cmake install fix

- micro_ros_setup/config/zephyr/generic/build.sh
- micro_ros_setup/config/zephyr/generic/client-colcon.meta
- micro_ros_setup/config/zephyr/generic/configure.sh
- micro_ros_setup/config/zephyr/generic/create.sh
- micro_ros_setup/scripts/build_firmware.sh
This PR updates the Zephyr build scrips for Foxy. It adds a transport configuration logic for Zephyr RTOS.
> Updated zephyr build scripts

- micro_ros_setup/config/freertos/crazyflie21/client_uros_packages.repos
- micro_ros_setup/config/freertos/olimex-stm32-e407/client_uros_packages.repos
- micro_ros_setup/config/host/generic/client_host_packages.repos
- micro_ros_setup/config/nuttx/generic/client-colcon.meta
- micro_ros_setup/config/nuttx/generic/client_uros_packages.repos
- micro_ros_setup/config/nuttx/generic/configure.sh
- micro_ros_setup/config/nuttx/generic/create.sh
- micro_ros_setup/config/nuttx/generic/flash.sh
- micro_ros_setup/config/zephyr/generic/client-colcon.meta
- micro_ros_setup/config/zephyr/generic/client_uros_packages.repos
This PR updates the Nuttx build scripts for the foxy release
> Updated Nuttx build system for Foxy

- micro_ros_setup/config/zephyr/generic/build.sh
This PR relax the Zephyr build script for allowing building not supported platforms
> Relax Zephyr build for more platforms

- .github/workflows/ci.yml
- NOTICE
- README.md
- config/zephyr/generic/build.sh
- config/zephyr/generic/flash.sh
- config/zephyr/generic/supported_platforms
- scripts/create_firmware_ws.sh
Add board support to the appropriate files.
'sudo apt update' was also taken out of create_firmware_ws.sh so that it doesn't need to be run as root. Not sure how best to catch the error that comes up if apt is not up to date, it is recommended in the tutorials to update before running, but perhaps that is not enough. 
These changes have been tested with serial transport only.
Note: In order to run examples without any modifications, this pull request will need to be merged in lockstep with changes to the [zephyr_apps repo here](https://github.com/micro-ROS/zephyr_apps/pull/18)
> Add support for nucleo_h743zi with Zephyr

- .github/workflows/ci.yml
- config/host/client_ros2_packages.txt
- config/host/generic/client_host_packages.repos
- config/host/generic/create.sh
- scripts/configure_firmware.sh
This PR ix micro-ROS host dependencies mix with ROS2 by using the system installed ROS 2 packages when available
Related to: https://github.com/micro-ROS/micro_ros_setup/issues/184
> Fix micro-ROS host dependencies mix with ROS2

- config/zephyr/generic/build.sh
- config/zephyr/list_apps.sh
This PR enables using external applications in Zephyr by using `UROS_CUSTOM_APP_FOLDER`
> Add custom app folder in Zephyr

- config/host/generic/build.sh
This PR adds build steps for `rosidl_typesupport_microxrcedds_c` and `rosidl_typesupport_microxrcedds_cpp` before building the whole micro-ROS workspace for host in order to generate the packages typesupport libraries correctly.
Related: https://github.com/ros2/rosidl/issues/520
Workaround for: https://github.com/micro-ROS/micro_ros_setup/issues/184
> Added lines to build typesupport earlier

- scripts/build_agent.sh
This PR disables the Agent CED middleware functionality when building a micro-ROS agent.
Solves https://github.com/micro-ROS/micro-ROS.github.io/issues/221
> Disable XRCE P2P Agent for micro-ROS

- NOTICE
- config/zephyr/generic/build.sh
- scripts/build_firmware.sh
Currently, the CMAKE_VERBOSE_MAKEFILE=ON setting in the zephyr build step creates a huge amount of build output. For most use-cases this provides very little additional information while obfuscating and hiding warnings and errors from own code.
This commit only introduces this flag and implements it for the zephyr rtos, but it can obviously later get used by other RTOS build scripts.
> Add -v cli flag to build step to control amount of build output

- config/host/generic/client_host_packages.repos
This PR add UUID packages to micro-ROS host in order to work with ROS 2 actions
> Added UUID to micro-ROS host

- config/zephyr/generic/flash.sh
This pr contains some cleanups and minor behavior changes which should make using and evolving the flash step in zephyr easier. The behavior changes are:
- The nucleo_h743zi platform should now work again, it seems there was a faulty indentation in the previous version.
- All platforms now check if the used build artifact (```zephyr.exe```/```zephyr.bin```) exists before using it.
- Console output should now be consistent between the platforms (obviously excluding the flash tool).
- The ```olimex-stm32-e407``` platform now runs the flashed firmware after resetting. This is consistent with what the ```west flash```-based platforms and the ```nucleo_h743zi``` platform do.
- The step now defaults to using ```west flash``` as opposed to special casing each and every supported platform. This …
> Improve flash step for zephyr RTOS

- scripts/build_agent.sh
This change avoids the necessity of including every new required package into the colcon `packages-select` list. Instead, we let colcon take care of the required dependencies to build the `micro_ros_agent` target.
> Improve build_agent.sh script

- .github/CODEOWNERS
- .github/workflows/ci.yml
- README.md
- config/freertos/nucleo_f767zi/board.repos
- config/freertos/nucleo_f767zi/build.sh
- config/freertos/nucleo_f767zi/client-colcon.meta
- config/freertos/nucleo_f767zi/client_uros_packages.repos
- config/freertos/nucleo_f767zi/configure.sh
- config/freertos/nucleo_f767zi/create.sh
- config/freertos/nucleo_f767zi/flash.sh
- config/freertos/nucleo_f767zi/package.xml
Related: https://github.com/micro-ROS/freertos_apps/pull/44
> Add port for Nucleo-F767ZI

- README.md
- config/zephyr/generic/create.sh
The previous zephyr-sdk version 0.11.2 installed by micro_ros_setup contained no cmake files and it relied to be found via the home directory. That's not necessary with 0.12.4 anymore and the zephyr-sdk downloaded by micro_ros_setup works standalone.
I also bumped zephyrs version to 2.6.0 as it contains some better board dts. In my case I made a full CAN bus app work on the nucleo f446re with microros support.
> bump zephyr version to 2.6.0; zephyr-sdk version to 0.12.4

- config/freertos/olimex-stm32-e407/flash.sh
The STLINK v2 debuggers can be used to flash the Olimex STM32-E407 board, and in fact that is what we use at SpaceRyde. Added support for them in the flash.sh script. This is not a foxy-specific change per se, but that is the ROS distribution we are currently using. If there is a nice way to include this change in galactic and main as well, let me know.
> Support for flashing Olimex STM32-E407 with STLINK v2 debuggers

- scripts/build_firmware.sh
- scripts/configure_firmware.sh
- scripts/flash_firmware.sh
In some places, the path to firmware is hardcoded instead of using the FW_TARGETDIR variable. This PR fixes it.
> Fix: Use $FW_TARGETDIR/ instead of firmware/

- config/host/generic/build.sh
- config/host/generic/client_host_packages.repos
- change build.sh to make sure to build libstd_msgs__rosidl_typesupport_microxrcedds_c.so and libstd_msgs__rosidl_typesupport_microxrcedds_cpp.so
- fix a typo in colcon.meta
> Build dynamic lib of rosidl_typesupport _microxrcedds

- config/zephyr/generic/create.sh
Currently the create.sh script only pulls down an x86 version of zephyr regardless of the arch of the system the user is building on.
We have a few people that are using M1 macbooks with Ubuntu VMs and this has been causing a bit of trouble since the workspace never gets setup correctly with the right toolchain.
Currently just for galactic but I can make another PR for other versions if necessary
Proposed fix: Read the arch of the system and pull down the aarch64 version if necessary. 
Using v0.13.1 for arm as that's what was recommended to me
> Modified zephyr create.sh to pull correct toolchain based on arch

- scripts/build_firmware.sh
- scripts/configure_firmware.sh
- scripts/create_firmware_ws.sh
- scripts/flash_firmware.sh
This PR fixes the incorrect logic in checking if the generic platform is being used.
https://github.com/micro-ROS/micro_ros_setup/issues/550 
Signed-off-by: Kevin Goez <kevin.goez@apex.ai>
> Fix logic for generic platform

- config/freertos/olimex-stm32-e407/flash.sh
Added support for flashing an Olimex STM32-E407 using a Segger J-Link debugger. Tested using the [FreeRTOS tutorial](https://micro.ros.org/docs/tutorials/core/first_application_rtos/freertos/) on humble with a clone of a Segger J-Link V9. Although it should work fine in other distributions and with an original debugger.
> Support Segger J-Link to flash Olimex E407
